auction/auction/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'www.views.home', name='home'),
    url(r'^login/$', 'www.views.my_login'),
    url(r'^register/$', 'www.views.register'),
    url(r'^accounts/', include('userprofiles.urls')),
    url(r'^logout_view/$', "www.views.logout_view", name='logout_view'),
    url( r'^activate/(?P<email>[\w\.-]+@[\w\.-]+)/$', 'www.views.activate' ),

    # url(r'^auction/', include('auction.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
)

auction/userprofiles/contrib/emailverification/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import patterns, url

auction/userprofiles/contrib/profiles/urls.py
from django.conf.urls.defaults import patterns, url


urlpatterns = patterns('userprofiles.contrib.profiles.views',
    url(r'^(?P<user_name>[a-zA-Z0-9._-]+)/$', 'profile',
        name='userprofiles_profile'),
    url(r'^change/$', 'profile_change',
        name='userprofiles_profile_change'),
    url(r'^portfolio/(?P<user_name>[a-zA-Z0-9._-]+)/$', 'get_gallery',
        name='userprofiles_gallery'),
)

auction/userprofiles/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import patterns, url, include

from django.conf import settings
from django.utils.translation import ugettext, ugettext_lazy as _
from django import forms

class MySetPasswordForm(forms.Form):
    """
    A form that lets a user change set his/her password without entering the
    old password
    """
    error_messages = {
        'password_mismatch': _("The two password fields didn't match."),
        'password_length': _("The length of the Passwords should be a min. 8 characters."),
    }
    new_password1 = forms.CharField(label=_("New password"),
                                    widget=forms.PasswordInput)
    new_password2 = forms.CharField(label=_("New password confirmation"),
                                    widget=forms.PasswordInput)

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(MySetPasswordForm, self).__init__(*args, **kwargs)

    def clean_new_password2(self):
        password1 = self.cleaned_data.get('new_password1')
        password2 = self.cleaned_data.get('new_password2')
        if password1 and password2:
            if password1 != password2:
                raise forms.ValidationError(
                    self.error_messages['password_mismatch'])
            if len(password1) < 8 or len(password2) < 8:
                raise forms.ValidationError(
                    self.error_messages['password_length'])
        return password2

    def save(self, commit=True):
        self.user.set_password(self.cleaned_data['new_password1'])
        if commit:
            self.user.save()
        return self.user

urlpatterns = patterns('userprofiles.views',
    url(r'^register/$', 'registration', name='userprofiles_registration'),
    url(r'^register/complete/$', 'registration_complete',
        name='userprofiles_registration_complete'),
)

if 'userprofiles.contrib.accountverification' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        (r'^activate/', include('userprofiles.contrib.accountverification.urls')),
    )

if 'userprofiles.contrib.emailverification' in settings.INSTALLED_APPS:
    # urlpatterns += patterns('',
    #     (r'^email/', include('userprofiles.contrib.emailverification.urls')),
    # )
    urlpatterns += patterns('userprofiles.contrib.emailverification.views',
    url(r'^settings/$', 'email_change', name='userprofiles_email_change'),
    url(r'^settings/email_change/$', 'email_change_save', name='email_change_save'),
    url(r'^settings/password_change/$', 'password_change_save', name='password_change_save'),
    url(r'^requested/$', 'email_change_requested',
        name='userprofiles_email_change_requested'),
    url(r'^verify/(?P<token>[0-9A-Za-z-]+)/(?P<code>[0-9A-Za-z-]+)/$',
        'email_change_approve', name='userprofiles_email_change_approve'),
)


if 'userprofiles.contrib.profiles' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        (r'^profile/', include('userprofiles.contrib.profiles.urls')),
    )

urlpatterns += patterns('django.contrib.auth.views',
    url(r'^logout/$', 'logout', {'template_name': 'userprofiles/logged_out.html'},
        name='auth_logout'),
    url(r'^password/change/$', 'password_change',
        {'template_name': 'userprofiles/password_change.html'},
        name='auth_password_change'),
    url(r'^password/change/done/$', 'password_change_done',
        {'template_name': 'userprofiles/password_change_done.html'},
        name='auth_password_change_done'),
    url(r'^password/reset/$', 'password_reset',
        {'template_name': 'userprofiles/password_reset.html',
         'email_template_name': 'userprofiles/mails/password_reset_email.html'},
        name='auth_password_reset'),
    url(r'^password/reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
        'password_reset_confirm',
        {'template_name': 'userprofiles/password_reset_confirm.html', 'set_password_form':MySetPasswordForm},
        name='auth_password_reset_confirm'),
    url(r'^password/reset/complete/$', 'password_reset_complete',
        {'template_name': 'userprofiles/registration.html', 'extra_context':{'pass_reset': True}},
        name='auth_password_reset_complete'),
    url(r'^password/reset/done/$', 'password_reset_done',
        {'template_name': 'userprofiles/registration.html', 'extra_context':{'email_sent': True}},
        name='auth_password_reset_done'),
)

auction/userprofiles/contrib/profiles/models.py
# -*- coding: utf-8 -*-

auction/userprofiles/models.py
# -*- coding: utf-8 -*-

auction/userprofiles/contrib/emailverification/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.sites.models import Site
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.utils.translation import ugettext_lazy as _

from userprofiles.contrib.emailverification.models import EmailVerification


class ChangeEmailForm(forms.Form):
    new_email = forms.EmailField(label=_('New e-mail address'), required=True)

    def clean_new_email(self):
        new_email = self.cleaned_data['new_email']

        user_emails = User.objects.filter(email__iexact=new_email).count()
        verification_emails = EmailVerification.objects.filter(
            new_email__iexact=new_email, is_expired=False).count()
        if user_emails + verification_emails > 0:
            raise forms.ValidationError(_('This email address is already in use. Please supply a different email address.'))

        return new_email

    def save(self, user=None):
        if not user:
            return None

        verification = EmailVerification.objects.create(user=user,
            old_email=user.email, new_email=self.cleaned_data['new_email'])

        context = {
            'user': user,
            'verification': verification,
            'site': Site.objects.get_current(),
        }

        subject = ''.join(render_to_string(
            'userprofiles/mails/emailverification_subject.html', context).splitlines())
        body = render_to_string('userprofiles/mails/emailverification.html', context)

        send_mail(subject, body, settings.DEFAULT_FROM_EMAIL,
            [self.cleaned_data['new_email'],])

        return verification

auction/userprofiles/contrib/profiles/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.utils.translation import ugettext_lazy as _

from userprofiles import settings as up_settings
from userprofiles.utils import UserProfile


class ProfileForm(forms.ModelForm):
    first_name = forms.CharField(label=_('First name'), required=False)
    last_name = forms.CharField(label=_('Last name'), required=False)
    email = forms.EmailField(label=_('E-mail'))

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)

        if not up_settings.PROFILE_ALLOW_EMAIL_CHANGE:
            del self.fields['email']
        else:
            self.fields.keyOrder.remove('email')
            self.fields.keyOrder.insert(0, 'email')

        if not up_settings.REGISTRATION_FULLNAME:
            del self.fields['first_name']
            del self.fields['last_name']
        else:
            self.fields.keyOrder.remove('first_name')
            self.fields.keyOrder.remove('last_name')
            self.fields.keyOrder.insert(0, 'first_name')
            self.fields.keyOrder.insert(1, 'last_name')

    def save(self, *args, **kwargs):
        obj = super(ProfileForm, self).save(*args, **kwargs)
        if up_settings.REGISTRATION_FULLNAME:
            obj.user.first_name = self.cleaned_data['first_name']
            obj.user.last_name = self.cleaned_data['last_name']

        if up_settings.PROFILE_ALLOW_EMAIL_CHANGE:
            obj.user.email = self.cleaned_data['email']

        if up_settings.REGISTRATION_FULLNAME or up_settings.PROFILE_ALLOW_EMAIL_CHANGE:
            obj.user.save()

        if hasattr(self, 'save_profile'):
            self.save_profile(obj, *args, **kwargs)

        return obj

    class Meta:
        model = UserProfile
        exclude = ('user',)

auction/userprofiles/contrib/accountverification/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, redirect

from userprofiles import settings as up_settings
from userprofiles.contrib.accountverification.models import AccountVerification
from django.contrib import messages
from django.utils import translation
from django.template import RequestContext
from django.shortcuts import redirect

def registration_activate(request, activation_key):
    activation_key = activation_key.lower()
    account = AccountVerification.objects.activate_user(activation_key)

    messages.info(request, translation.gettext("Your account is now activated"))
    return redirect('/log_in/', context_instance=RequestContext(request))

    # return render(request, 'userprofiles/registration_activate.html', {
    #     'account': account,
    #     'expiration_days': up_settings.ACCOUNT_VERIFICATION_DAYS
    # })

auction/userprofiles/contrib/emailverification/views.py
# -*- coding: utf-8 -*-
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.forms import PasswordChangeForm
from django import forms
from django.utils import translation

from userprofiles import settings as up_settings
from userprofiles.contrib.emailverification.forms import ChangeEmailForm
from userprofiles.contrib.emailverification.models import EmailVerification



@login_required
def email_change(request):
    post_change_redirect = reverse('django.contrib.auth.views.password_change_done')
    password_change_form = PasswordChangeForm
    if request.method == 'POST':
        print 'it is post'
        password_form = password_change_form(user=request.user, data=request.POST)
        email_form = ChangeEmailForm(request.POST)
        if password_form.is_valid():
            password_form.save()
            return redirect(post_change_redirect)
        if email_form.is_valid():
            verification = email_form.save(request.user)
            return redirect('userprofiles_email_change_requested')
        email_form = ChangeEmailForm()
        password_form = password_change_form(user=request.user)
    else:
        email_form = ChangeEmailForm()
        password_form = password_change_form(user=request.user)

    return render(request, 'userprofiles/email_change.html', {'email_form': email_form, 'password_form': password_form, 'password_length_valid':True})

def email_change_save(request):
    post_change_redirect = reverse('django.contrib.auth.views.password_change_done')
    password_change_form = PasswordChangeForm
    if request.method == 'POST':
        password_form = password_change_form(user=request.user, data=request.POST)
        email_form = ChangeEmailForm(request.POST)
        if password_form.is_valid():
            password_form.save()
            return redirect(post_change_redirect)
        if email_form.is_valid():
            verification = email_form.save(request.user)
            return redirect('userprofiles_email_change_requested')
        password_form = password_change_form(user=request.user)
    else:
        email_form = ChangeEmailForm()
        password_form = password_change_form(user=request.user)

    return render(request, 'userprofiles/email_change.html', {'email_form': email_form, 'password_form': password_form, 'password_length_valid':True})

def password_change_save(request):
    password_length_valid = True
    post_change_redirect = reverse('django.contrib.auth.views.password_change_done')
    password_change_form = PasswordChangeForm
    if request.method == 'POST':
        password_form = password_change_form(user=request.user, data=request.POST)
        email_form = ChangeEmailForm(request.POST)
        if password_form.is_valid():
            print len(password_form.cleaned_data["new_password1"])
            if len(password_form.cleaned_data["new_password1"]) > 7:
                password_form.save()
                return redirect(post_change_redirect)
            else :
                password_length_valid = False
        if email_form.is_valid():
            verification = email_form.save(request.user)
            return redirect('userprofiles_email_change_requested')
        email_form = ChangeEmailForm()
    else:
        email_form = ChangeEmailForm()
        password_form = password_change_form(user=request.user)

    return render(request, 'userprofiles/email_change.html', {'email_form': email_form, 'password_form': password_form, 'password_length_valid': password_length_valid})


@login_required
def email_change_requested(request):
    return render(request, 'userprofiles/email_change_requested.html', {
        'expiration_days': up_settings.EMAIL_VERIFICATION_DAYS})


@login_required
def email_change_approve(request, token, code):
    try:
        verification = EmailVerification.objects.get(token=token, code=code,
            user=request.user, is_expired=False, is_approved=False)

        verification.is_approved = True
        verification.save()
        messages.success(request, _(u'E-mail address changed to %(email)s' % {
            'email': verification.new_email}))
    except EmailVerification.DoesNotExist:
        messages.error(request,
            _(u'Unable to change e-mail address. Confirmation link is invalid.'))

    return redirect(up_settings.EMAIL_VERIFICATION_DONE_URL)

auction/userprofiles/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from userprofiles import settings as up_settings
from userprofiles.utils import get_form_class
from django.contrib import messages
from django.utils import translation
from django.template import RequestContext


def registration(request):
    RegistrationForm = get_form_class(up_settings.REGISTRATION_FORM)

    if request.method == 'POST':
        form = RegistrationForm(data=request.POST, files=request.FILES)

        if form.is_valid():
            new_user = form.save()
            
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            request.session['login'] = "first"

            # Automatically log this user in
            if up_settings.AUTO_LOGIN:

                if up_settings.EMAIL_ONLY:
                    username = form.cleaned_data['email']

                user = authenticate(username=username, password=password)
                if user is not None:
                    if user.is_active:
                        login(request, user)

            return redirect(up_settings.REGISTRATION_REDIRECT)

    else:
        form = RegistrationForm()

    import random
    x = random.randint(1, 7)
    try:
        next = request.GET['next']
    except:
        next = ''
    return render(request, 'userprofiles/registration.html', {'form': form, 'pic_num': x,'next':next})


def registration_complete(request):
    messages.info(request, translation.gettext("An activation mail has been sent, please activate your account in order to login"))
    return redirect('/', context_instance=RequestContext(request))
    # return render(request, 'userprofiles/registration_complete.html', {
    #     'account_verification_active': up_settings.USE_ACCOUNT_VERIFICATION,
    #     'expiration_days': up_settings.ACCOUNT_VERIFICATION_DAYS,
    # })

auction/auction/templates/userprofiles/password_reset.html
<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en" class="cufon-active cufon-ready">
<head>
{% block meta %}
<title>Auction</title> {% endblock %}
<link rel="stylesheet" href="{{STATIC_URL}}css/main-ltr.css" type="text/css" media="screen" />
{% block styles %} {% endblock %}
<script type="text/javascript" src="{{STATIC_URL}}js/jquery.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}js/cufon.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}js/Museo_Sans_100_250.font.js"></script>
<script>
	Cufon.replace('.title h3');
</script>

{% block scripts %} {% endblock %}
</head>
{% load i18n %}
<body>
	<div id="header">
		<div id="header-content">
			<div id="nav">
				<ul>
                    <li><a href="/">Home</a></li>
					<li>{% trans "How it Works?" %}</li> {% if not user.is_authenticated %}
					<li><a href="/register/">Register</a><span class="arrow">&rarr;</li> 
					{% else %}
					<li><a href="/logout_view/">Logout</a><span class="arrow">&rarr;</li> 
					{% endif %}
				</ul>
			</div>
			<p class="slogan">Auction</p>
		</div>
	</div>
	<div id="wrapper">
		<div id="loginwrapper" style="height: 200px;min-height: 200px;">
			<div id="login"style="height: 125px;">			
				<form action="." method="post">
				{%  csrf_token %}
					<p>
					<font color="#f3592a">{{ form.email.errors }}</font>
						<span class="field"> <input id="id_email" type="text" name="email" maxlength="75" placeholder="{% trans 'Email' %}" class="input-xlarge" style="height:30px;" value="{% if form.email.value %}
                        {{ form.email.value }}
                    {% endif %}"/>
						</span>
					</p>
					<div class="submitdiv">
						<input type="submit" value="Reset Password">
					</div>
				</form>
			</div>
		</div>
	</div>
</body>
</html>

auction/auction/templates/userprofiles/password_reset_complete.html
<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en" class="cufon-active cufon-ready">
<head>
{% block meta %}
<title>Auction</title> {% endblock %}
<link rel="stylesheet" href="{{STATIC_URL}}css/main-ltr.css" type="text/css" media="screen" />
{% block styles %} {% endblock %}
<script type="text/javascript" src="{{STATIC_URL}}js/jquery.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}js/cufon.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}js/Museo_Sans_100_250.font.js"></script>
<script>
	Cufon.replace('.title h3');
</script>

{% block scripts %} {% endblock %}
</head>
{% load i18n %}
<body>
	<div id="header">
		<div id="header-content">
			<div id="nav">
				<ul>
                    <li><a href="/">Home</a></li>
					<li>{% trans "How it Works?" %}</li> {% if not user.is_authenticated %}
					<li><a href="/register/">Register</a><span class="arrow">&rarr;</li> 
					{% else %}
					<li><a href="/logout_view/">Logout</a><span class="arrow">&rarr;</li> 
					{% endif %}
				</ul>
			</div>
			<p class="slogan">Auction</p>
		</div>
	</div>
	<h1>Reset Password</h1>

    <p>
        Your password has benn updated successfully
        <br />
        <a href="/">Back to Login ?</a>
    </p>
</body>
</html>

auction/auction/templates/userprofiles/password_reset_confirm.html
<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en" class="cufon-active cufon-ready">
<head>
{% block meta %}
<title>Auction</title> {% endblock %}
<link rel="stylesheet" href="{{STATIC_URL}}css/main-ltr.css" type="text/css" media="screen" />
{% block styles %} {% endblock %}
<script type="text/javascript" src="{{STATIC_URL}}js/jquery.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}js/cufon.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}js/Museo_Sans_100_250.font.js"></script>
<script>
	Cufon.replace('.title h3');
</script>

{% block scripts %} {% endblock %}
</head>
{% load i18n %}
<body>
	<div id="header">
		<div id="header-content">
			<div id="nav">
				<ul>
                    <li><a href="/">Home</a></li>
					<li>{% trans "How it Works?" %}</li> {% if not user.is_authenticated %}
					<li><a href="/register/">Register</a><span class="arrow">&rarr;</li> 
					{% else %}
					<li><a href="/logout_view/">Logout</a><span class="arrow">&rarr;</li> 
					{% endif %}
				</ul>
			</div>
			<p class="slogan">Auction</p>
		</div>
	</div>
	<div id="wrapper">
		<div id="loginwrapper" style="height: 400px;min-height: 400px;">
			<div id="login"style="height: 250px;">			
				<form action="." method="post">
				{%  csrf_token %}
					<p>
					<font color="#f3592a">{{ form.new_password2.errors }}</font>
						<span class="field"> <input type="password" name="new_password1" id="id_new_password1" placeholder="New Password">
						</span>
					</p>
					<p>
						<span class="field"> <input type="password" name="new_password2" id="id_new_password2" placeholder="Confirm New Password}">
						</span>
					</p>
					<div class="submitdiv">
						<input type="submit" value="Reset Password">
					</div>
				</form>
			</div>
		</div>
	</div>
</body>
</html>

auction/auction/templates/userprofiles/password_reset_done.html
<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en" class="cufon-active cufon-ready">
<head>
{% block meta %}
<title>Auction</title> {% endblock %}
<link rel="stylesheet" href="{{STATIC_URL}}css/main-ltr.css" type="text/css" media="screen" />
{% block styles %} {% endblock %}
<script type="text/javascript" src="{{STATIC_URL}}js/jquery.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}js/cufon.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}js/Museo_Sans_100_250.font.js"></script>
<script>
	Cufon.replace('.title h3');
</script>

{% block scripts %} {% endblock %}
</head>
{% load i18n %}
<body>
	<div id="header">
		<div id="header-content">
			<div id="nav">
				<ul>
                    <li><a href="/">Home</a></li>
					<li>{% trans "How it Works?" %}</li> {% if not user.is_authenticated %}
					<li><a href="/register/">Register</a><span class="arrow">&rarr;</li> 
					{% else %}
					<li><a href="/logout_view/">Logout</a><span class="arrow">&rarr;</li> 
					{% endif %}
				</ul>
			</div>
			<p class="slogan">Auction</p>
		</div>
	</div>
	<h1>Reset password</h1>

    <p>
        We sent you an e-mail including a link. Please click the
        link to continue resetting your password. Thank you!
    </p>
</body>
</html>

auction/auction/templates/userprofiles/registration.html
<!DOCTYPE html>
{% if request.session.django_language == 'ar' %}
    <html dir="rtl">
{% else %}
    <html dir="ltr">
{% endif %}
    <head>
        {% load i18n %}
        <title>  Shoghlanah </title>
        <link rel="shortcut icon" href="{{ STATIC_URL }}img/favicon.ico" />
        <link rel="stylesheet" href="{{STATIC_URL}}css/jquery-ui-1.8.20.custom.css">
        <link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/bootstrap.min.css"/>
        <link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/jquery.validate.css" />
        <link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/jquery-ui/jquery-ui-1.8.16.custom.css"/>
        <link href='http://fonts.googleapis.com/css?family=Raleway:300,400,200,600' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/fonts.css"/>
        <link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/bootstrap-edits.css"/>
        {% if request.session.django_language == 'ar' %}
            <link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/bootstrap-edits-rtl.css"/>
        {% endif %}
        <link rel="stylesheet" type="text/css" href="{{STATIC_URL}}assets/css/master.css"/>
        {% if request.session.django_language == 'ar' %}
            <link rel="stylesheet" type="text/css" href="{{STATIC_URL}}assets/css-rtl/master-rtl.css"/>
        {% endif %}
        <link rel="stylesheet" type="text/css" href="{{STATIC_URL}}assets/css/registration.css"/>
        {% if request.session.django_language == 'ar' %}
            <link rel="stylesheet" type="text/css" href="{{STATIC_URL}}assets/css-rtl/registration-rtl.css"/>
        {% endif %}
        <link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/shadowbox/shadowbox.css">
        <script type="text/javascript" src="{{STATIC_URL}}js/jquery-1.8.0.min.js"></script>
        <script type="text/javascript" src="{{STATIC_URL}}js/jquery-ui-1.8.23.custom.min.js"></script>
        <script type="text/javascript" src="{{STATIC_URL}}js/jquery.placeholder.min.js"></script>
        <script type="text/javascript" src="{{STATIC_URL}}js/noty/jquery.noty.js"></script>
        <script type="text/javascript" src="{{STATIC_URL}}js/noty/layouts/top.js"></script>
        <script type="text/javascript" src="{{STATIC_URL}}js/noty/themes/default.js"></script>
        <script type="text/javascript" src="{{STATIC_URL}}js/shadowbox/shadowbox.js"></script>
        <script type="text/javascript" src="{{STATIC_URL}}js/bootstrap.min.js"></script>
        <script type="text/javascript">
            Shadowbox.init();
            $(document).ready(function() {
                    {% if pass_reset %}
                    var n = noty({
                        layout: 'top',
                        text: "{% trans 'Your password has been successfully updated' %}",
                        type: 'success',
                        timeout: '3500'
                    });
                     {% endif %}
                    {% if email_sent %}
                        var n = noty({
                            layout: 'top',
                            text: '{% trans "An e-mail was sent to you, including a link to continue resetting your password" %}',
                            type: 'success',
                            timeout: '4000'
                        });
                     {% endif %}
                $('input, textarea').placeholder();
                $('#login-btn').click(function() {
                    var hasError = false;
                    var emailReg = /^([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?$/;
                    var emailaddressVal = $("#username").val();
                    if(emailaddressVal == '') {
                        $('#login-info').html('{% trans "Please Enter Your Email." %}');
                        hasError = true;
                    }
             
                    else if(!emailReg.test(emailaddressVal)) {
                        $('#login-info').html('{% trans "Enter A Valid Email Address." %}');
                        hasError = true;
                    }

                    var password = $("#password").val();
                    if(password == '') {
                        $('#login-info').html('{% trans "Please Enter Your Password." %}');
                        hasError = true;
                    }
             
                    if(hasError == true) { return false; }
                });


                $('#invitation-btn').click(function() {
                    var hasError = false;
                    var emailReg = /^([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?$/;
                    var emailaddressVal = $("#email").val();
                    if(emailaddressVal == '') {
                        $('#invitation-info').html('{% trans "Please Enter Your Email." %}');
                        hasError = true;
                    }
             
                    else if(!emailReg.test(emailaddressVal)) {
                        $('#invitation-info').html('{% trans "Enter A Valid Email Address." %}');
                        hasError = true;
                    }
                    if(hasError == true) { return false; }
        _kmq.push(['record', 'Requested Invitation to join ',{'User':emailaddressVal}]);
        _gaq.push(['_trackEvent', 'Registration', 'Requested Invitation', emailaddressVal]);        
                });
            });
        </script>
    </head>

    <body style="background-image: url('{{ STATIC_URL }}img/login/login{% if pic_num %}{{pic_num}}.png');{% else %}1.png');{% endif %}">
        <div class="title">
        </div>

        <div class="form well" id="login-form">
            <label class="signup-info" id="login-info" style="width:197px;">
                {{ error_message }}
            </label>
            <label class="label-login">{% trans "Sign Up" %}</label>
            <hr class="divider-grey"/>
            <form action="/log_in/" method="post" class="form-login">
                {% csrf_token %}
                <input id="username" class="username" type="text" name="username" maxlength="75" placeholder='{% trans "Email" %}' style="background-image: url({{STATIC_URL}}assets/img/01.png)"/>
                <input id="password" type="password" name="password" maxlength="75" placeholder='{% trans "Password" %}' style="background-image: url({{STATIC_URL}}assets/img/02.png);">
                <input class="btn-signin" id="login-btn" type="submit" value="{% trans 'Register' %}">
                <input type="hidden" name="next" value="/" />
            </form>
            <br/>
            <br/>
            <hr class="divider-grey"/>
        </div>
    </body>
</html>